version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: postgres_tsp_db
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASS: postgres
      DJANGO_DB_PORT: "5432"
      DJANGO_DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
      ml_service:
        condition: service_started
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://app:8000
    depends_on:
      - app

  ml_service:
    build:
      context: ./ml_service # путь к директории с нейросетью
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_tsp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_tsp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
