# Generated by Django 5.1.7 on 2025-03-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("imageID", models.AutoField(primary_key=True, serialize=False)),
                ("link_to_image", models.URLField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("userName", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Usage_history",
            fields=[
                ("operationID", models.AutoField(primary_key=True, serialize=False)),
                ("prompt", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=50)),
                (
                    "imageID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gena_database_app.image",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gena_database_app.user",
                    ),
                ),
            ],
        ),
    ]
