# Generated by Django 5.1.7 on 2025-03-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gena_database_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage_history",
            name="imageID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gena_database_app.image",
            ),
        ),
        migrations.AlterField(
            model_name="usage_history",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
