# Generated by Django 5.1.3 on 2025-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gena_database_app', '0002_alter_usage_history_imageid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
        migrations.RenameModel(
            old_name='Usage_history',
            new_name='UsageHistory',
        ),
    ]
