# Generated by Django 5.1.3 on 2025-03-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gena_database_app', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagehistory',
            name='uuID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
