# Generated by Django 5.1.7 on 2025-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gena_database_app", "0005_usagehistory_uuid_delete_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usagehistory",
            old_name="uuID",
            new_name="modelPromptID",
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="link_to_image",
            field=models.TextField(),
        ),
    ]
