# Generated by Django 5.1.7 on 2025-03-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gena_database_app", "0006_rename_uuid_usagehistory_modelpromptid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagemodel",
            old_name="link_to_image",
            new_name="image_base64",
        ),
    ]
