# Generated by Django 5.1.7 on 2025-04-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gena_database_app", "0009_remove_user_username_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagehistory",
            name="modelPromptID",
        ),
    ]
