spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/gena
    username: postgres
    password: secret
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:myuser}
    password: ${RABBITMQ_PASSWORD:secret}

app:
  security:
    jwt:
      issuer: generatorgena
      access-token-ttl: 15m
      secret-base64: ${JWT_SECRET}

  rabbitmq:
    topology:
      commands-exchange: ${GENERATION_COMMANDS_EXCHANGE:generation.commands}
      events-exchange: ${GENERATION_EVENTS_EXCHANGE:generation.events}

      requests-queue: ${GENERATION_REQUESTS_QUEUE:generation.requests}
      results-queue: ${GENERATION_RESULTS_QUEUE:generation.results}

      generate-routing-key: ${GENERATION_GENERATE_ROUTING_KEY:generation.generate}
      events-routing-pattern: ${GENERATION_EVENTS_ROUTING_PATTERN:generation.*}

  storage:
    minio:
      endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
      bucket: ${MINIO_BUCKET:generated-assets}

logging:
  exception-conversion-word: "%ex{short}"
  level:
    root: warn
    org.flowersinvase.backend: info
  file:
    name: ${LOG_FILE:logs/app.log}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
